name: alarm
description: A simple Flutter alarm manager plugin for both iOS and Android.
version: 2.2.0
homepage: https://github.com/gdelataillade/alarm

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_fgbg: ^0.3.0
  flutter_local_notifications: ^15.1.0
  plugin_platform_interface: ^2.1.4
  shared_preferences: ^2.1.2  
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/long_blank.mp3
    - assets/not_blank.mp3

  plugin:
    platforms:
      android:
        package: com.gdelataillade.alarm.alarm
        pluginClass: AlarmPlugin
      ios:
        pluginClass: AlarmPlugin